modLoader = "javafml"
loaderVersion = "[43,)"
license = "MIT"

[[mods]]
modId = "fableforged"
version = "${version}"
displayName = "FableForged"
description = "A collection of origins that we thought would be great idea."

displayURL = "https://www.curseforge.com/minecraft/mc-mods/origins-plus-plus"
issueTrackerURL = "https://github.com/QuantumXenon/origins-plus-plus/issues"
authors = "Skritek"
credits = "Skritek, Just_Vict0r, Kaii0Sky."
logoFile = "icon.png"

[[dependencies.fableforged]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"

[[dependencies.fableforged]]
modId = "origins"
mandatory = true
versionRange = "[1.19.2-1.7.1.1,)"

[[dependencies.fableforged]]
modId = "pehkui"
mandatory = true
versionRange = "[3.4.0,)"

[[dependencies.fableforged]]
modId = "xlpackets"
mandatory = true
versionRange = "[1.18.2-2,)"

[[dependencies.fableforged]]
modId = "apugli"
mandatory = true
versionRange = "[2.6.6,)"